config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  put "/orders/rating", to: "orders#rating", as: :order_rating
  get "orders/all", to: "orders#all_orders", as: :all_orders
  post "orders/all", to: "orders#reports", as: :reports
  get "menus/all", to: "menus#all", as: :all_menus
  resources :menus, :menu_items, :orders, :order_items, :users
  get "/about", to: "home#about"
  get "/cart", to: "orders#cart", as: :cart
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/sign_in", to: "sessions#new", as: :new_session
  post "/sign_in", to: "sessions#create", as: :session
  delete "/sign_out", to: "sessions#destroy", as: :destroy_session
  get "search", to: "search#search", as: :search
  patch "/users/:id/change_role", to: "users#change_role", as: :change_role
  
end

app/models/menu.rb
class Menu < ApplicationRecord
    # created by cmd
    # rails generate model MenuItems name:string description:string price:integer menu_id:integer
    has_many :menu_items, dependent: :destroy
    validates :name, presence: true, length: { in: 3..25 }, uniqueness: true
  
    def self.check_menu_exists_create_if_not(menu_name, new_menu_name)
      menu_name == "Others" ?
        Menu.new(name: new_menu_name.capitalize) :
        find(menu_name)
    end
    def self.active
      all.where("active = ?", true)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # created by cmd
  # rails generate controller Menus
  before_action :ensure_owner_logged_in, only: [:destroy, :all]

  def index
    @menus = Menu.order(:name)
    @order = current_user.orders.being_created
  end

  def all
    @menus = Menu.order(:name)
  end

  def show
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    menu = Menu.find(params[:id])
    menu.update(name: params[:name].capitalize,
                active: params[:active])
    if menu.save
      redirect_to(menus_path, notice: "#{menu.name} menu updated successfully!")
    else
      flash[:error] = menu.errors.full_messages
      redirect_to edit_menu_path
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy!
    respond_to do |format|
      format.html { redirect_to(menus_path, notice: "#{@menu.name} menu is deleted successfully!") }
      format.js
    end
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_menuList.html.erb
<div class="cafeteria-menu" id="cafeteria-menu">
  <ul>
    <% menus.each do |menu| %>
      <li class="menu"
          id=<%= "menu-#{menu.id}" %>
          <% if !menu.active && blur %>
            style="opacity:0.55"
          <% end %>
      >
        <% if @current_user.is_owner? %>
          <span class="menuItem-delete">
            <%= link_to menu,
                        method: :delete,
                        data: {confirm: 'Are you sure?'},
                        remote: true do%>
              <%= image_tag "trash.png" %>
            <% end %>
            <%= link_to edit_menu_path(menu.id) do%>
              <%= image_tag "edit-26.png" %>
            <% end %>
          </span>
        <% end %>
        <a href =<%= "#menuList-#{menu.id}" %>  class=<%= menu.id %> id="menuName"><%= menu.name.titlecase %></a>
      </li>
    <% end %>
  </ul>
</div>

app/views/menus/_mobileMenuList.html.erb
<div class="mobileMenuList">
  <div class="menuButton">
    <%= image_tag "plate.png" %>
    Menus
  </div>
  <% if order %>
    <% if order.order_items.any? %>
      <div class="cart-bottom">
        <span class="cart-bottom-items"> <%= pluralize(order.order_items.count,"item") %> </span>
        <span class="cart-bottom-price"> ₹<%= order.total_price %></span>
        <span class="cart-bottom-button"> <%= link_to "View Cart", cart_path %>
        </span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/menus/_search-addItem.html.erb
<% content_for :head do %>
  <% unless @current_user.is_owner? %>
    <div class="search-box">
      <form>
        <input type="search" placeholder="Search for item">
        <span class="submit-button">
        <input type="submit" value="Seach Item">
        </span>
      </form>
    </div>
  <% end %>
  <% if @current_user.is_owner? %>
    <div class="all-menus-link">
      <%= link_to "All menus", all_menus_path %>
    </div>
    <div class="addItem-form" id="addItem-form">
      <%= form_with(model: @menu, url: menu_items_url, method: "post", local: true) do |form|%>
        <p class="menus-dropdown">
          <select name="menu_name" id="menu-name">
            <option value="" disabled selected style="color:#7e808c">Select Menu to add</option>
            <% Menu.order(:name).each do |menu|%>
              <option value=<%= menu.id %>> <%= menu.name %> </option>
            <% end %>
            <option value="Others"> Others </option>
          </select>
        </p>
        <%= form.text_field :name, placeholder:"Item name" %>
        <%= form.number_field :price, placeholder:"Item price", in:1..10000 %>
        <%= form.text_field :description, placeholder:"Description of item" %>
        <%= form.text_field :new_menu_name, placeholder:"Menu name", class:"add-menu-input"%>
        <%= form.submit data: { "disable-with": "Saving..." } %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/menus/all.html.erb
<div class="active-menus-heading" >
  <h3>
    Active and Inactive Menus
  </h3>
</div>
<div class="menu-menuItems">
  <%= render partial: "menuList",locals: { menus: @menus, blur: true} %>
  <div class="cafeteria-menuItems">
    <% @menus.each do |menu| %>
      <ul class="menuItems-list" id=<%= "menuList-#{menu.id}" %>>
        <h3 class="menuName" id=<%= menu.id %>>
          <%= menu.name.titlecase %>
        </h3>
        <% menu.menu_items.order(:name).each do |menu_item| %>
          <li class="menuItem"
              id=<%= "item-#{menu_item.id}" %>
              <% unless menu_item.active && menu_item.menu.active %>
                style="opacity:0.55"
              <% end %>
          >
            <%= render partial: "menu_items/menuItems-list",
                       locals: { menu_item: menu_item } %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>
<!-- for mobile view -->
<%= render partial: "mobileMenuList", locals: { order: @order } %>

app/views/menus/destroy.js.erb
$("#menu-<%= @menu.id %>").hide(500);
$("#menuList-<%= @menu.id %>").hide(500);
$(".all-messages").html("<%= j (render partial: 'home/messages',
                                       locals: {notice: "#{@menu.name} menu is deleted successfully!" }) %>").hide().fadeIn(800);

app/views/menus/edit.html.erb
<main class="signUpBox">
  <p class="signUp-login">
    Edit menu
  </p>
  <%= form_with url: menu_path, method: :patch, class: "signUp-form" do |form| %>
    <p class="Active">
      <%= label_tag(:active,"Active") %>
      <%= form.check_box :active,
                        checked: @menu.active
      %>
    </p>
    <br>
    <%= form.text_field :name,
                        placeholder: "Menu Name",
                        value: @menu.name,
                        autofocus:"autofocus"
    %>
    <br>
    <%= form.submit "Update", data: { "disable-with": "Updating..." }, class: "signUp-button"%>
  <%end%>
</main>

app/views/menus/index.html.erb
<%= render partial: "search-addItem" %>
<% if @current_user.is_clerk? || @current_user.is_owner? %>
  <div class="active-order-heading">
    <h3>
        Active menus
    </h3>
  </div>
<% end %>
<!-- menu and menu items -->
<div class="menu-menuItems">
  <%= render partial: "menuList",locals: { menus: @menus.active, blur: false } %>
  <div class="cafeteria-menuItems">
    <% @menus.active.each do |menu| %>
      <ul class="menuItems-list" id=<%= "menuList-#{menu.id}" %>>
        <h3 class="menuName" id=<%= menu.id %>>
          <%= menu.name.titlecase %>
        </h3>
        <% menu.menu_items.active.order(:name).each do |menu_item| %>
          <li class="menuItem" id=<%= "item-#{menu_item.id}" %>>
            <%= render partial: "menu_items/menuItems-list",
                       locals: { menu_item: menu_item } %>
            <p class="orderItem-add" id=<%= "additem-#{menu_item.id}" %>>
              <%= render partial: "menu_items/addItem",
                       locals: { menu_item: menu_item, order: @order } %>
            </p>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>
<!-- for mobile view -->
<%= render partial: "mobileMenuList", locals: { order: @order } %>