config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  put "/orders/rating", to: "orders#rating", as: :order_rating
  get "orders/all", to: "orders#all_orders", as: :all_orders
  post "orders/all", to: "orders#reports", as: :reports
  get "menus/all", to: "menus#all", as: :all_menus
  resources :menus, :menu_items, :orders, :order_items, :users
  get "/about", to: "home#about"
  get "/cart", to: "orders#cart", as: :cart
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/sign_in", to: "sessions#new", as: :new_session
  post "/sign_in", to: "sessions#create", as: :session
  delete "/sign_out", to: "sessions#destroy", as: :destroy_session
  get "search", to: "search#search", as: :search
  patch "/users/:id/change_role", to: "users#change_role", as: :change_role
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  validates :name, presence: true, length: { in: 3..50 }
  validates :email, presence: true, uniqueness: true, email: true
  #validates :password, length: { in: 4..25 }

  def is_clerk?
    clerk = role == "clerk" ? true : false
  end

  def is_owner?
    owner = role == "owner" ? true : false
  end

  def self.clerks
    where("role = ?", "clerk")
  end

  def self.customers
    where("role = ?", "customer")
  end

  def self.get_user_by_email(email)
    user = all.where("email = ?", email).exists? ? find_by(email: email) : false
  end

  def alter_role(role1)
    #if role == "customer"
      #self.role = "clerk"
    #else
      #self.role = "customer"
    #end
    #save!
    if role!=role1
      self.role= role1
      save!
    end
  end

  def self.owners
    all.where("role = ? ", "owner")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in, only: [:create, :new]
  before_action :ensure_owner_logged_in, only: [:index]

  def new
    if current_user
      redirect_to(menus_path, notice: "Your'e already signed up user")
    end
  end

  def index
    @clerks = User.clerks.order(:id)
    @customers = User.customers.order(:id)
    @owners = User.owners
  end

  def create
    name, email = params[:name], params[:email]
    password = params[:password]
    password_confirmation = params[:password_confirmation]
    user = User.new(name: name.capitalize,
                    email: email,
                    role: "customer",
                    password: password,
                    password_confirmation: password_confirmation)
    if user.save && password.length > 4
      OrderMailer.with(user: user).welcome_user.deliver_now
      session[:current_user_id] = user.id
      redirect_to(menus_path, notice: "Welcome #{user.name}!")
    else
      flash[:error] = user.errors.full_messages + password(password)
      redirect_to new_user_path
    end
  end

  def edit
  end

  def update
    user, password = current_user, params[:password]
    password_confirmation = params[:password_confirmation]
    current_password = params[:current_password]
    if user.authenticate(current_password)
      if password == password_confirmation
        user.update!(password: password)
        redirect_to(menus_path, notice: "Password updated successfully")
      else
        redirect_to(edit_user_path, alert: "New passwords doesnt match")
      end
    else
      redirect_to(edit_user_path, alert: "Your current password is incorrect")
    end
  end

  def change_role
    @user = User.find(params[:id])
    @user.alter_role(params[:change_to_role])
    redirect_to(users_path, notice: "#{@user.name} role is changed to #{@user.role} ")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user-details.html.erb
<h3>
  <th colspan="5" class="table-header"><%= heading %></th>
</h3>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Email</th>
  <th>Orders</th>
  <th>Action</th>
</tr>
<% roles.each do |role| %>
    <tr class="user-row" id=<%= role.id %>>
      <td><%= role.id %></td>
      <td><%= role.name %></td>
      <td><%= role.email %></td>
      <td>
        <% role.orders.delivered_and_confirmed.ids.each do |id| %>
          <%= link_to id, "orders/all##{id}" %>,
        <% end %>
      </td>
      <td>
        <li class="cafeteria-navbarButton dropdown">
        <span class="change-role-btn">Change role </span>
        <div class="user-content">
          <ul class="change-role-dropdown">
          <% if role.role != "customer" %>
          <li>
            <div class="change-role-btn">
              <%= link_to "Make as Customer",
                      change_role_path(role.id,change_to_role: "customer"),
                      method: :patch,
                      data: {confirm: "Are you sure?",disable: "Please wait.."}
              %>
          </div>
          </li>
          <%end%>
          <% if role.role != "clerk" %>
          <li>
            <div class="change-role-btn">
              <%= link_to "Make as Clerk",
                      change_role_path(role.id,change_to_role: "clerk"),
                      method: :patch,
                      data: {confirm: "Are you sure?",disable: "Please wait.."}
              %>
          </div>
          </li>
          <%end%>
          <% if role.role != "owner" %>
          <li>
            <div class="change-role-btn">
              <%= link_to "Make as owner",
                      change_role_path(role.id,change_to_role: "owner"),
                      method: :patch,
                      data: {confirm: "Are you sure?",disable: "Please wait.."}
              %>
          </div>
          </li>
          <%end%>
          </ul>
          </div>
        </li>
      </td>
    </tr>
<% end %>

app/views/users/edit.html.erb
<main class="updateUser-box">
  <p class="signUp-login">
    Change your password
  </p>
  <%= form_with url: user_path, method: :put,id: "edit_user" do |form| %>
    <%= form.password_field :password,
                             placeholder: "New Password",
                             autofocus:"autofocus",
                             minlength: 4
    %>
    <br>
    <%= form.password_field :password_confirmation,
                             placeholder: "Conifrm new Password",
                             autofocus: true
    %>
    <br>
    <%= form.password_field :current_password,
                             placeholder: "Current Password",
                             autofocus: "autofocus"
    %>
    <br>
    <%= form.submit "Update",class:"signUp-button" %>
  <% end %>
</main>

app/views/users/index.html.erb
<main class="all-users">
  <% content_for :search do %>
    <div class="search-box">
      <%= form_with(url: search_path, method: "get", local: true) do |form|%>
        <%= form.text_field :email, placeholder: "Enter email of user" %>
        <%= form.submit "Search User", placeholder: "Enter email of user" %>
      <% end %>
    </div>
  <% end %>
  <section>
    <table class="all-clerks">
      <%= render partial: "user-details", locals: {roles: @owners, owners: @owners, heading: "Owner"} %>
      <%= render partial: "user-details", locals: {roles: @clerks, owners: nil, heading: "Clerks"} %>
      <%= render partial: "user-details", locals: {roles: @customers, owners: nil, heading: "Customers"} %>
    </table>
  </section>
</main>

app/views/users/new.html.erb
<main class="signUpBox">
  <p class="signUp-login">
    Already have an account?
    <br>
    <%= link_to "Login here", new_session_path, class:"login-link" %>
  </p>
  <%= form_with url: users_path, class: "signUp-form" do |form| %>
    <%= form.text_field :name,
                         placeholder: "Name",
                         autofocus:"autofocus"
    %>
    <br>
    <%= form.email_field :email,
                          placeholder: "Email",
                          autofocus:"autofocus"
    %>
    <br>
    <%= form.password_field :password,
                             placeholder: "Password",
                             autofocus:"autofocus",
                             minlength: 4
    %>
    <br>
    <%= form.password_field :password_confirmation,
                             placeholder: "Confirm Password",
                             autofocus:"autofocus"
    %>
    <br>
    <%= form.submit "Sign up",data: { "disable-with": "Signing up..." }, class: "signUp-button"%>
  <%end%>
</main>