config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  put "/orders/rating", to: "orders#rating", as: :order_rating
  get "orders/all", to: "orders#all_orders", as: :all_orders
  post "orders/all", to: "orders#reports", as: :reports
  get "menus/all", to: "menus#all", as: :all_menus
  resources :menus, :menu_items, :orders, :order_items, :users
  get "/about", to: "home#about"
  get "/cart", to: "orders#cart", as: :cart
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/sign_in", to: "sessions#new", as: :new_session
  post "/sign_in", to: "sessions#create", as: :session
  delete "/sign_out", to: "sessions#destroy", as: :destroy_session
  get "search", to: "search#search", as: :search
  patch "/users/:id/change_role", to: "users#change_role", as: :change_role
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :ensure_user_logged_in
  
    def index
      current_user
    end

    def about
      current_user
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_messages.html.erb
<div class="all-messages">
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <%end%>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <%end%>
  <% if flash[:error] %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(flash[:error].count, "error") %> prohibited this FORM being saved:
      </h2>
      <ul>
        <% flash[:error].each_with_index do |msg,index| %>
          <li class="error-msg"><%= "#{index + 1}.#{msg}" %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/home/_navbar.html.erb
<nav class="cafeteria-navbar">
  <h2 class="cafeteria-navbarHeading">
    <%= image_tag "logo.png" %>YammiFood
    <div class="container">
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>
    </div>
  </h2>
  <ul class="cafeteria-navbarAllButtons" id="cafeteria-navbarAllButtons">
    <% if @current_user %>
      <li class="cafeteria-navbarButton">
        <i class="fa fa-home"></i>
        <%= link_to "Home", menus_path %>
      </li>
      <% if @current_user.is_clerk? || @current_user.is_owner? %>
        <li class="cafeteria-navbarButton">
          <i class="fa fa-hourglass-half" aria-hidden="true"></i>
          <%= link_to "Pending Orders", pending_orders_path %>
        </li>
      <% end %>
      <% if @current_user.is_owner? %>
        <li class="cafeteria-navbarButton">
          <i class="fa fa-list-alt" aria-hidden="true"></i>
          <%= link_to "All Orders", all_orders_path %>
        </li>
        <li class="cafeteria-navbarButton">
          <i class="fa fa-users" aria-hidden="true"></i>
          <%= link_to "Users", users_path %>
        </li>
      <% end %>
      <li class="cafeteria-navbarButton">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <%= link_to "Cart", cart_path %>
      </li>
      <li class="cafeteria-navbarButton">
          <%= image_tag "logout.png" %>
          <%= link_to "LogOut", destroy_session_path, method: :delete %>
      </li>
      <li class="cafeteria-navbarButton dropdown">
        <span class="name-icon"><%= @current_user.name[0] %></span><%= @current_user.name %>
        <div class="user-content">
          <ul>
            <li>
              <i class="fa fa-shopping-bag" aria-hidden="true"></i>
              <%= link_to "My Orders", orders_path %>
            </li>
            <li>
              <i class="fa fa-pencil" aria-hidden="true"></i>
              <%= link_to "Edit Profile", edit_user_path(id: @current_user.id) %>
            </li>
          </ul>
        </div>
      </li>
      <li class="cafeteria-navbarButton mobile">
        <i class="fa fa-shopping-bag" aria-hidden="true"></i>
        <%= link_to "My Orders", orders_path %>
      </li>
      <li class="cafeteria-navbarButton mobile">
        <i class="fa fa-pencil" aria-hidden="true"></i>
        <%= link_to "Edit Profile", edit_user_path(id: @current_user.id) %>
      </li>
      <li class="cafeteria-navbarButton mobile">
        <i class="fa fa-sign-out" aria-hidden="true"></i>
        <%= link_to "LogOut", destroy_session_path, method: :delete %>
      </li>
    <% else %>
      <li class="cafeteria-navbarButton">
        <%= image_tag "sign-in.png" %>
        <%= link_to "Sign In", new_session_path %>
      </li>
      <li class="cafeteria-navbarButton">
        <%= image_tag "sign-up.png" %>
        <%= link_to "Sign Up", new_user_path %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/home/about.html.erb
<section class="home-main-pic delivery">
  <%= image_tag "food_delivery_vehicle.png"%>
  <div class="about_us_div">
    <p class="about_us_1">We at YammiFood make fresh food available at your doorstep within less time.</p>
    <br/><br/>
    <p class="about_us_1">Our restaurant started in 2010 and we came very far and long since then but we provide our customers with good food .</p> 
  </div>
</section>

app/views/home/index.html.erb
<section >
<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">1 / 4</div>
  <%= image_tag "icecream_image.png"%>
  <div class="text">Juicy IceCreams</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 4</div>
   <%= image_tag "fastfood_image.png"%>
  <div class="text">Yummy Burgers</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">3 / 4</div>
   <%= image_tag "biryani.png"%>
  <div class="text">Special Biryani</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">4 / 4</div>
   <%= image_tag "sizzler.png"%>
  <div class="text">Sizzlers</div>
</div>


<a class="prev" onclick="plusSlides(-1)">&#10094;</a>
<a class="next" onclick="plusSlides(1)">&#10095;</a>

</div>
<br>

<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
  <span class="dot" onclick="currentSlide(4)"></span> 
</div>
</section>

<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}
</script>