config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  put "/orders/rating", to: "orders#rating", as: :order_rating
  get "orders/all", to: "orders#all_orders", as: :all_orders
  post "orders/all", to: "orders#reports", as: :reports
  get "menus/all", to: "menus#all", as: :all_menus
  resources :menus, :menu_items, :orders, :order_items, :users
  get "/about", to: "home#about"
  get "/cart", to: "orders#cart", as: :cart
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/sign_in", to: "sessions#new", as: :new_session
  post "/sign_in", to: "sessions#create", as: :session
  delete "/sign_out", to: "sessions#destroy", as: :destroy_session
  get "search", to: "search#search", as: :search
  patch "/users/:id/change_role", to: "users#change_role", as: :change_role
  
end

app/models/order.rb
class Order < ApplicationRecord
  # created by cmd
  # rails generate model MenuItems date:datetime user_id:integer delivered_at:datetime
  has_many :order_items
  belongs_to :user

  def self.delivered_and_confirmed
    where.not("status = ? ", "being_created")
  end

  def self.pending_orders
    where("status= ?", "order_confirmed")
  end

  def self.being_created
    where("status= ?", "being_created").first
  end

  def order_status
    if status == "being_created"
      "Being created"
    elsif status == "order_confirmed"
      "Order Confirmed"
    else
      "Delivered at #{delivered_at.strftime("%d %B,%Y - %I:%M %p")}"
    end
  end

  def total_price
    price = 0
    order_items.each { |item| price = price + item.menu_item_price}
    price
  end

  def order_item(menu_item_name)
    order_items.where(menu_item_name: menu_item_name).first
  end

  def all_menu_item_names
    order_items.order(:menu_item_name).map { |item| item.menu_item_name }
  end

  def self.get_order_by_id(id)
    order = all.where("id = ?", id).exists? ? find(id) : false
  end

  def self.get_reports(user_id, from_date, to_date)
    #puts" user_id :#{user_id} , from date : #{from_date} , to date : #{to_date} ,#{user_id!=""} , #{from_date!=""} , #{to_date!=""} , #{user_id !="" && from_date!="" && to_date!=""} ,#{from_date!="" && to_date!=""} "
    if (user_id !="" && from_date!="" && to_date!="")
      #puts" if"
      all.where("user_id = ? and date >= ? and date <= ?", user_id, from_date, to_date)
    elsif (from_date!="" && to_date!="")
      #puts"elsif 1"
      all.where("date >= ? and date <= ?", from_date, to_date)
    elsif (user_id!="")
      #puts" elseif 2"
      all.where(user_id: user_id)
    else
      #puts" else"
      all
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # created by cmd
  # rails generate controller Orders
  before_action :ensure_owner_logged_in, only: [:all_orders, :reports]
  before_action :ensure_owner_or_clerk_logged_in, only: [:pending_orders, :update]

  def index
    orders = current_user.orders.order(:id)
  end

  def show
  end

  def pending_orders
  end

  def create
    @order = current_user.orders.being_created
    if @order.order_items.empty?
      redirect_to(cart_path, alert: "Order must have atleast 1 item")
    else
      @order.status = "order_confirmed"
      @order.date = Time.now
      @order.save!
      OrderMailer.with(order: @order, user: current_user).order_confirmation.deliver_now
      OrderMailer.with(order: @order).new_order_placed.deliver_now
      redirect_to(menus_path, notice: "Order recived! Soon your order will be delivered")
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.status = "order_delivered"
    @order.delivered_at = Time.now
    @order.save!
    OrderMailer.with(order: @order, user: @order.user).order_delivered.deliver_now
    respond_to do |format|
      format.html { redirect_to("/pending_orders", notice: "#{@order.id} is marked as delivered!") }
      format.js
    end
  end

  def cart
    @order = current_user.orders.being_created
    #@cart_count=current_user.orders.total_cart_items
  end

  def all_orders
    @all_orders = Order.order(id: :desc)
  end

  def rating
    @order = Order.find(params[:id])
    @order.ratings = params[:rating]
    @order.save!
    @order.order_items.rate_menu_items(params[:rating])
    respond_to do |format|
      format.html { redirect_to(orders_path, notice: "Thank you for rating the order id:#{@order.id}") }
      format.js
    end
  end




  def reports
    @found = params[:user_id].present? ? User.where("id = ?", params[:user_id].to_i).exists? : true
    @all_orders = Order.get_reports(params[:user_id],
                                    params[:from_date],
                                    params[:to_date]).order(id: :desc)

    #puts" all orders: #{all_orders.all.to_a}"
    respond_to do |format|
      format.html { redirect_to("/orders/all", notice: "This are all the orders between mentioned dates ") }
      format.js
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_empty-cart.html.erb
<h3 class="empty-cart">Uh oh! Your cart is empty</h3>
<div class="empty-cart-img">
  <%= image_tag "empty-cart.jpg" %>
</div>
<div class="addItems">
  <%= link_to "Add Items +", menus_path %>
</div>

app/views/orders/_ordersList.html.erb
<div class="all-orders">
  <% orders.each do |order| %>
    <div class="each-order" id="<%= order.id %>">
      <p>
        <span>Order Id:
          <%= order.id %>
        </span>
        <span class="total-price">Rs.<%= order.total_price %></span>
      </p>
      <p class="ordered_at">
        <% if order.user.is_clerk? || order.user.is_owner? %>
          <%= image_tag "walk-in1.png" %>
          <%= "Walk In Customer" %>
        <% else %>
          <%= order.user.name.titlecase %>
        <% end %>
        <% if order.date %>
          <%= formated_time(order.date) %>
        <% end %>
      </p>
      <p class="rating-and-status">
        <%= render partial: "rating", locals: {order: order, mark_as_delivered: mark_as_delivered } %>
        <p class="each-order-status"
            <% if order.delivered_at %>
              style="color:#11b911;font-weight:bold"
            <% elsif order.date %>
              style="color:#ff6000e8;font-weight:bold"
            <% else %>
              style="color:rgba(159, 49, 250, 0.932);font-weight:bold"
            <% end %>
        >
          <%= order.order_status %>
        </p>
      </p>
      <section class="order-details" id="order-details">
        <ul>
          <% order.all_menu_item_names.uniq.each do |menu_item| %>
            <li class="order-item" >
              <span>
                <%= menu_item + " x"+order.all_menu_item_names.count(menu_item).to_s %>
              </span >
              <span class="total-price">
                Rs.<%= order.order_items.get_menu_item_price(menu_item)*order.all_menu_item_names.count(menu_item) %>
              </span>
            </li>
          <% end %>
        </ul>
      </section>
    </div>
  <% end %>
</div>

app/views/orders/_rating.html.erb
<p class="rate" id=<%= "order-#{order.id}" %>>
  <% if mark_as_delivered %>
    <%= link_to "Mark as Delivered",
                order_path(order.id),
                method: "patch",
                data: { "disable-with": "Please wait...", confirm: "Are you sure?" },
                remote: true
    %>
  <% elsif order.delivered_at.nil? %>
    Order is being prepared
  <% else %>
    <% if order.ratings == 0 && order.user == @current_user %>
      <% 5.times do |img| %>
        <%= link_to order_rating_path(id: order.id, rating: img+1),
                    method: :put,
                    remote: true,
                    class:"rating" do
        %>
        <%= image_tag "star.png" , id:img+1 %>
      <% end %>
    <% end %>
  <% else %>
    <% order.ratings.times do %>
      <%= image_tag "ratted-star.png" %>
    <% end %>
    <% (5-order.ratings).times do %>
      <%= image_tag "star.png" %>
    <% end %>
  <% end %>
<%end%>
</p>

app/views/orders/all_orders.html.erb
<div class="orders">
  <% content_for :search do %>
    <div class="search-box">
      <%= form_with(url: search_path, method: "get", local: true) do |form|%>
        <%= form.text_field :order_id, placeholder: "Enter order id" %>
        <%= form.submit "Search order" %>
      <% end %>
    </div>
    <div class="sales-reports">
      <%= form_with(url: reports_path,method: :post) do |form|%>
        <%= form.number_field :user_id,
                             placeholder: "User ID",
                             min: 1%>
        <%= form.date_field :from_date,
                            placeholder: "From date",
                            min: Date.parse("30-06-2019"),
                            max: Date.today %>
        <%= form.date_field :to_date,
                            placeholder: "To date",
                            max: Date.today %>
        <%= form.submit "Submit" %>
      <%end%>
    </div>
  <% end %>
  <h3 class="orders-heading">All Orders</h3>
  <%= render partial:"ordersList",
             locals: { orders: @all_orders.delivered_and_confirmed,
                       mark_as_delivered: false } %>
</div>

app/views/orders/cart.html.erb
<div class="cart">
  <h3 class="cart-heading">Cart</h3>
  <% if @order %>
    <% if @order.order_items.empty? %>
      <%= render partial: "empty-cart" %>
    <% else %>
      <div class="cart-item-price">
        <p class="cart-item-heading" >
          <span>Item Name</span >
          <span class="total-price">Price</span>
        </p>
        <ul>
          <% @order.all_menu_item_names.uniq.each do |menu_item_name| %>
            <li class="cart-item" >
              <span><%= menu_item_name %></span >
              <span class="total-price">
                <p class="cartItem-add">
                  <%= link_to "-",
                            order_item_path(id: @order.order_item(menu_item_name).id, cart: 1),
                            {:method => :delete} %>
                  <%= @order.all_menu_item_names.count(menu_item_name) %>
                  <%= link_to "+",
                              order_items_path(menu_item_id: @order.order_item(menu_item_name).menu_item_id, cart: 1),
                              {:method => :post} %>
                </p>
                <p class="qty-price">
                  Rs.<%= @order.order_items.get_menu_item_price(menu_item_name)*
                         @order.all_menu_item_names.count(menu_item_name) %>
                </p>
              </span>
            </li>
          <% end %>
        </ul>
        <p class="cart-total-price" >
          <span>Total Price</span >
          <span class="total-price"><%= @order.total_price %></span>
        </p>
        <%= form_with(model: @order, url: orders_path, method: "post", local: true) do |form| %>
          <%= form.submit "Checkout",data: { "disable-with": "Processing..." },class:"cart-checkout" %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <%= render partial: "empty-cart" %>
  <% end %>
</div>

app/views/orders/index.html.erb
<div class="orders">
  <h3 class="orders-heading">Your Orders</h3>
  <%= render partial:"ordersList",
             locals: { orders: @current_user.orders.order(id: :desc).delivered_and_confirmed,
                       mark_as_delivered: false } %>
</div>

app/views/orders/pending_orders.html.erb
<div class="orders">
  <h3 class="orders-heading">Pending Orders</h3>
  <%= render partial:"ordersList",
             locals: { orders: Order.order(:id).pending_orders,
                       mark_as_delivered: true } %>
</div>

app/views/orders/rating.js.erb
$("#order-<%= @order.id%>").html("<%= j (render partial: 'rating',
                                                locals: { order: @order,
                                                          mark_as_delivered: false }) %>").hide().fadeIn(800);
$(".all-messages").html("<%= j (render partial: 'home/messages',
                                       locals: {notice: "Thank you for rating order with id:#{@order.id}" }) %>").hide().fadeIn(800);

app/views/orders/reports.js.erb
$(".all-orders").hide(500);
$(".all-orders").html("<%= j (render partial: 'ordersList',
                                       locals: {orders: @all_orders.delivered_and_confirmed,
                                       mark_as_delivered: false }) %>").hide().fadeIn(800);
<% if @found %>
  $(".all-messages").html("<%= j (render partial: 'home/messages',
                                         locals: {notice: pluralize(@all_orders.delivered_and_confirmed.count, "Order")})
                            %>").hide().fadeIn(800);
<% else %>
  $(".all-messages").html("<%= j (render partial: 'home/messages',
                                       locals: {alert: "User not found" }) %>").hide().fadeIn(800);
<% end %>

app/views/orders/update.js.erb
$("#<%= @order.id%>").fadeOut(800);
$(".all-messages").html("<%= j (render partial: 'home/messages',
                                       locals: {notice: "#{@order.id} is marked as delivered!" }) %>").hide().fadeIn(800);